foodUsageSystem/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('foodutility.urls')),
]

foodutility/urls.py
from django.urls import path
from foodutility import views
urlpatterns = [
    path('',views.home,name="homepage" ),
    path('signup/', views.signup, name='signup'),
    path('login_view/',views.login_view,name="login_view"),
    path('logout/',views.logout_view,name="logout_view"),
    path('volunteer/',views.volunteer,name="volunteer"),
    path('donator/',views.donator,name="donator"),
    path('donator/chooseDonate/money/',views.money,name="d-money"),
    path('donator/chooseDonate/',views.chooseDonate,name="choose_donate"),
    path('donator/chooseDonate/food/',views.food,name="d-food"),
    path('volunteer/history',views.history,name="history"),
]

foodutility/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

class CustomUser(AbstractUser):
    ROLE_CHOICES = [
        ('volunteer', 'Volunteer'),
        ('donator', 'Donator'),
    ]

    role = models.CharField(max_length=20, choices=ROLE_CHOICES, default='donator')
    phone = models.CharField(max_length=15, blank=True, null=True)
    def __str__(self):
        return self.username

class Volunteer_Detail(models.Model):
    username = models.CharField(max_length=122, blank=True, null=True)
    phone = models.BigIntegerField(max_length=15, blank=True, null=True)
    email = models.CharField(max_length=122, blank=True, null=True)
    city =  models.CharField(max_length=122, blank=True, null=True)
    foodName =  models.CharField(max_length=122, blank=True, null=True)
    quantity =  models.CharField(max_length=122, blank=True, null=True)
    duedate = models.DateField(default = "2003-12-11")
    def __str__(self):
        return self.username
    
class Donor_Detail(models.Model):
    username = models.CharField(max_length=122, blank=True, null=True)
    phone = models.BigIntegerField(max_length=15, blank=True, null=True)
    email = models.CharField(max_length=122, blank=True, null=True)
    city =  models.CharField(max_length=122, blank=True, null=True)
    def __str__(self):
        return self.username
    
class Donate_Money(models.Model):
    donor = models.CharField(max_length=122, blank=True, null=True)
    volunteer = models.CharField(max_length=122, blank=True, null=True)
    amount = models.DecimalField(decimal_places = 4,max_digits = 10)
    reason = models.CharField(max_length=122, blank=True, null=True)
    date = models.DateTimeField()
    def __str__(self):
        return self.donor
    
class Donate_Food(models.Model):
    donor = models.CharField(max_length=122, blank=True, null=True)
    volunteer = models.CharField(max_length=122, blank=True, null=True)
    foodName =  models.CharField(max_length=122, blank=True, null=True)
    quantity =  models.CharField(max_length=122, blank=True, null=True)
    date = models.DateTimeField()
    def __str__(self):
        return self.donor
    

foodutility/views.py
from django.contrib.auth import login,authenticate,logout
from django.shortcuts import render, redirect
from .models import CustomUser,Volunteer_Detail,Donor_Detail,Donate_Money,Donate_Food
from django.contrib import messages
from datetime import datetime,date
from django.utils.dateparse import parse_date
def home(request):
    return render(request,'home.html')

def signup(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        confirm_password = request.POST['confirm_password']
        email = request.POST['email']
        role = request.POST['role']
        phone = request.POST['phone']
        #validations::
        
        if len(phone)>10 or len(phone)<10:
            messages.error(request,"invalid phone number")
            return redirect('homepage')
        
        if(password!=confirm_password):
            messages.error(request,"enter correct as above password")
            return redirect('homepage')
        user = CustomUser.objects.create_user(username=username, password=password, email=email, role=role,phone=phone)
        
        return redirect('login_view')  

    return render(request, 'signup.html')

def login_view(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        
        user = authenticate(request,username=username,password=password)
        
        if user is not None:
            login(request,user)
            if user.role == 'volunteer':
                request.session['user_username'] = user.username
                return redirect('volunteer')
            else:
                request.session['user_username'] = user.username
                return redirect('donator')
                 
        else:
            messages.success(request,"invalid credentials")
            return redirect('homepage')
    
    return render(request,'login.html')

def logout_view(request):
    logout(request)
    messages.success(request,"logged OUT")
    return redirect('homepage')

def volunteer(request):
    if request.method == "POST":
       username = request.user.username
       phone = request.user.phone
       email = request.user.email
       city = request.POST.get('city')
       foodname = request.POST.get('foodname')
       qty = request.POST.get('qty')
       duedate = request.POST.get('duedate')
       custom_date = datetime.strptime(duedate, '%Y-%m-%d').date()
       vol = Volunteer_Detail(username=username,phone = phone,email=email,city=city,foodName=foodname,quantity=qty,duedate=custom_date)
       vol.save()
    return render(request,'volunteer.html')

def donator(request):
    if request.method == 'POST':
        username = request.user.username
        username = request.user.username
        phone = request.user.phone
        email = request.user.email
        city = request.POST.get('city')
        donor = Donor_Detail(username=username,phone = phone,email=email,city=city)
        donor.save()
    return render(request,'donator.html')

def money(request):
    
    if request.method == 'POST':
        donor = request.user.username
        volunteer = request.POST.get('vol')
        amount = request.POST.get('amount')
        reason = request.POST.get('reason')
        date = datetime.today()
        md = Donate_Money(donor=donor,volunteer=volunteer,amount=amount,reason=reason,date=date)
        md.save()
    donor_detail = Donor_Detail.objects.filter(username=request.user.username).first()
    get_city = donor_detail.city
    get_volunteers = Volunteer_Detail.objects.filter(city=get_city)
    return render(request,'money.html',{'get_volunteers': get_volunteers})

def food(request):
    if request.method == 'POST':
       donor = request.user.username
       volunteer = request.POST.get('vol')
       food_detail = Volunteer_Detail.objects.filter(username=volunteer).first()
       foodname = food_detail.foodName
       quantity = food_detail.quantity
       date = datetime.today()
       fd = Donate_Food(donor=donor,volunteer=volunteer,foodName=foodname,quantity=quantity,date=date)
       fd.save()
       food_detail.delete()
    donor_detail = Donor_Detail.objects.filter(username=request.user.username).first()
    get_city = donor_detail.city
    get_volunteers = Volunteer_Detail.objects.filter(city=get_city)
    
    return render(request,'food.html',{'get_volunteers': get_volunteers})   

def chooseDonate(request):
    return render(request,'donation_options.html')

def history(request):
    get_money_details = Donate_Money.objects.filter(volunteer=request.user.username)
    get_food_details = Donate_Food.objects.filter(volunteer=request.user.username)
    return render(request,'history.html',{'get_money_details': get_money_details , 'get_food_details':get_food_details})

templates/donation_options.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Choose To donate</title>
</head>
<body>
    {% csrf_token %}
{% if user.is_authenticated%}
    <a href="{% url 'logout_view' %}"><button>Logout</button></a>
    <a href="money"><button>Money</button></a><br><br>
    <a href="food"><button>Food</button></a><br>
{%endif%}
</body>
</html>

templates/donator.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Donator</title>
</head>
<body>
{% if user.is_authenticated%}
    <a href="{% url 'logout_view' %}"><button>Logout</button></a>
    {% if request.session.user_username %}
    <p>Logged in as: {{ request.session.user_username }}</p>
    {% else %}
    <a href="logout"><button>Logout</button></a>
    <p>Not logged in</p>
    {% endif %}
    <form action="{% url 'donator' %}" method="post">
        {% csrf_token %}
        <div>
            <label for="city">City: </label>
            <select name="city" id="city" required>
                <option value="Vadodara">Vadodara</option>
                <option value="Nadiad">Nadiad</option>
                <option value="Junagadh">Junagadh</option>
            </select>
        </div>
        <div>
            
            <button type="submit">Save</button><br><br>
            <a href="chooseDonate">Choose Ways to Donate</a>
        </div>
    </form>
{%endif%}
</body>
</html>

templates/food.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Food Donations</title>
</head>
<body>
{% if user.is_authenticated%}
    <a href="{% url 'logout_view' %}"><button>Logout</button></a>
      <h1>Volunteers' requests in your city: </h1>
      <form method="post">
         {%csrf_token%}
         {% if get_volunteers %}
            {% for volunteer in get_volunteers %}
            <input type="radio" id="vol" name="vol" value="{{volunteer.username}}">
            <label for="vol">{{volunteer.username }}</label><br>
            <p>{{volunteer.foodName}}</p>
            <p>{{volunteer.quantity}}</p>
            <p>{{volunteer.duedate}}</p>
            <br><br><br>
            {% endfor %}
        {%else%}
            <p>No volunteers found in your city</p>
         {%endif%}
         <button type="submit">Donate</button>
      </form>
{%endif%}
</body>
</html>

templates/history.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Donation History</title>
</head>
<body>
    {%csrf_token%}
{% if user.is_authenticated%}
    <a href="{% url 'logout_view' %}"><button>Logout</button></a>
    <h1>Successfully Received Donations: </h1>

         <h3>Money Donated: </h3>
         {% if get_money_details %}
            {% for donor in get_money_details %}
            
            <p>{{donor.donor}}</p>
            <p>{{donor.amount}}</p>
            <p>{{donor.reason}}</p>
            <p>{{donor.date}}</p>
            <br><br><br>
            {% endfor %}
        {%else%}
            <p>No volunteers found in your city</p>
         {%endif%}

         <h3>Food Donated: </h3>
         {% if get_food_details %}
            {% for donor in get_food_details %}
            
            <p>{{donor.donor}}</p>
            <p>{{donor.foodName}}</p>
            <p>{{donor.quantity}}</p>
            <p>{{donor.date}}</p>
            <br><br><br>
            {% endfor %}
        {%else%}
            <p>No volunteers found in your city</p>
         {%endif%}
{%endif%}
</body>
</html>

templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home</title>
</head>
<body>
    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
            <li>{{ message }}</li>
        {% endfor %}
    </ul>
{% endif %}
    <h1>Welcome To Food Utility System</h1>
    <h3>Signup if new</h3>
    <a href="signup"><button>Sign-Up</button></a>
    <h5>Or login</h5>
    <a href="login_view"><button>Login</button></a>
</body>
</html>

templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
</head>
<body>
    <h2>Login</h2>
    
    <form method="post" action="{% url 'login_view' %}">
        {% csrf_token %}
        
        <!-- Username -->
        <div>
            <label for="id_username">Username:</label>
            <input type="text" name="username" id="id_username" required>
        </div>
        
        <!-- Password -->
        <div>
            <label for="id_password">Password:</label>
            <input type="password" name="password" id="id_password" required>
        </div>

        <!-- Submit Button -->
        <div>
            <button type="submit">Login</button>
        </div>
    </form>

</body>
</html>

templates/money.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Donate Money</title>
</head>
<body>
{% if user.is_authenticated%}
    <a href="{% url 'logout_view' %}"><button>Logout</button></a>
    <form  method="post">
        {%csrf_token%}
        <label for="vol">Select Volunteers: </label><br><br>
        {% if get_volunteers %}
        <select name="vol" id="vol" required>
            {% for volunteer in get_volunteers %}
            <option value="{{volunteer.username}}">{{volunteer.username}}</option>
            {% endfor %}
        </select>
        <br>
        {%else%}
           <p>No volunteers found in your city</p>
        {%endif%}
        <label for="amount">Donate Amount: </label>
        <input type="number" name="amount">

        <label for="comment">Reason: </label>
        <input type="text" name="reason">
        <button type="submit">Donate</button>
</form>
{%endif%}
</body>
</html>

templates/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sign Up</title>
</head>
<body>
    <h2>Sign Up</h2>
    
    <form method="post" action="{% url 'signup' %}">
        {% csrf_token %}
        
        <!-- Username -->
        <div>
            <label for="id_username">Username:</label>
            <input type="text" name="username" id="id_username" required>
        </div>

        <!-- Password -->
        <div>
            <label for="id_password">Password:</label>
            <input type="password" name="password" id="id_password" required>
        </div>
        <div>
            <label for="id_password">Confirm Password:</label>
            <input type="password" name="confirm_password" id="id_password" required>
        </div>
        <!-- Email -->
        <div>
            <label for="id_email">Email:</label>
            <input type="email" name="email" id="id_email" required>
        </div>
       
        <!-- Role -->
        <div>
            <label for="id_role">Role:</label>
            <select name="role" id="id_role" required>
                <option value="volunteer">Volunteer</option>
                <option value="donator">Donator</option>
            </select>
        </div>
        <!-- Phone -->
        <div>
            <label for="id_email">Phone:</label>
            <input type="phone" name="phone" id="id_email" required>
        </div>
        <!-- Submit Button -->
        <div>
            <button type="submit">Sign Up</button>
        </div>
    </form>

</body>
</html>

templates/volunteer.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Volunteer</title>
</head>
<body>

{% if user.is_authenticated%}
    <a href="{% url 'logout_view' %}"><button>Logout</button></a>
    {% if request.session.user_username %}
    <p>Logged in as: {{ request.session.user_username }}</p>
    {% else %}
    <p>Not logged in</p>
    {% endif %}
    <form action="{% url 'volunteer' %}" method="post">
        {% csrf_token %}
        <div>
            <label for="city">City: </label>
            <select name="city" id="city" required>
                <option value="Vadodara">Vadodara</option>
                <option value="Nadiad">Nadiad</option>
                <option value="Junagadh">Junagadh</option>
            </select>
        </div>
        <h2>Requirements: </h2>
        <label for="food-name">Food Name</label>
        <input type="text" name="foodname">

        <label for="qty">Quantity: </label>
        <input type="text" name="qty">

        <label for="enddate">Due Date: </label>
        <input type="date" name="duedate">
        <div>
            <button type="submit">Save</button>
        </div>

    </form>
    <a href="history"><button>Received Donations</button></a>
{%endif%}
</body>
</html>